### ISSUE TITLE
Difficulty running extract-games.js

### ISSUE THREAD

**Issue by bzlister** [octachrome/treason#27]
I can run the overall project and play on the localhost page, but when I just try to run extract-games.js to get the data, I get the following error:

module.js:549
    throw err;
    ^

Error: Cannot find module './game-tracker'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (c:\Users\bzlis\Documents\coup\db\extract-games.js:5:21)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

Any ideas? I mainly just want the data for a machine learning project so it would be awesome if someone could email me the zip file, provided there is no easy fix to the problem above.

**Comment by bzlister** [comment]
Solved. Change line 5 of extract-games.js from
`const GameTracker = require('./game-tracker');`
to
`const GameTracker = require('../game-tracker');`
