### ISSUE TITLE
Database apparently empty?

### ISSUE THREAD

**Issue by bzlister** [octachrome/treason#28]
When running extract-games.js:

{ CouchError: not_found: Database does not exist.
    at Request._onResponse [as _callback] (c:\Users\bzlis\Documents\coup\node_modules\cradle\lib\cradle.js:241:29)
    at Request.self.callback (c:\Users\bzlis\Documents\coup\node_modules\request\request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (c:\Users\bzlis\Documents\coup\node_modules\request\request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (c:\Users\bzlis\Documents\coup\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
  name: 'CouchError',
  message: 'not_found: Database does not exist.',
  error: 'not_found',
  reason: 'Database does not exist.',
  headers: 
   { 'cache-control': 'must-revalidate',
     'content-length': '58',
     'content-type': 'application/json',
     date: 'Tue, 09 Apr 2019 20:32:52 GMT',
     server: 'CouchDB/2.3.1 (Erlang OTP/19)',
     'x-couch-request-id': 'bc52c0623b',
     'x-couchdb-body-time': '0',
     status: 404 } }

Looking through treason_db on Fauxton in my browser, the only files I see are _design/games, game_stats, and game_versions. Am I missing something? Where are the 4GB of uncompressed data?

**Comment by octachrome** [comment]
This wasn't intended for public use, I just committed the script there so I could keep track of it. The games database is available in JSON format here: https://www.dropbox.com/sh/8rkos46std12mqd/AACcVOf0q9vn2WgBgUgiEhwDa?dl=0

**Comment by octachrome** [comment]
Sure, it'd be great to hear about your ideas. What kind of algorithm do you have in mind?

**Comment by bzlister** [comment]
Likely some combination of decision trees, imitation learning, and regression.
